#!/usr/bin/env bash

CACHE=./.mvndelta-cache
if [ ! -f "$CACHE" -a -n "$WITHCACHE" ] || [ -z "$WITHCACHE" ]; then
    fd --type f -e xml -x echo {//} \;  | sort > "$CACHE" 
elif [ -n "$WITHCACHE" ]; then
    echo "Using cache"
fi

mvn_modules=$(
git diff HEAD~1 --name-only | while read f ; do
    while [ -n "$f" ] ; do 
        [ "$f" = "${f%/*}" ] && break; # guard against top level file changes (no basename)
        f=${f%/*};
        [ -f "${f}/pom.xml" ] && rg -w "^./${f}$" $CACHE && { # found the closest directory with pom.xml to the changed file
            echo $f;
            break
        }
    done
done | sort -u | while read changed_module ; do
    yq '[.project.groupId,.project.artifactId] | join(":")' "${changed_module}/pom.xml";
    echo
done | sort -u | paste -sd, -
)
echo mvn ${mvn_modules:+-pl $mvn_modules} $@
mvn ${mvn_modules:+-pl $mvn_modules} $@
